# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.ImageField(choices=[(1, 'Main'), (2, 'Competition')], default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
