# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcb', '0002_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.IntegerField(choices=[(1, 'Main'), (2, 'Competition')]),
        ),
    ]
