# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-09 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcb', '0005_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default=1, upload_to='player/img'),
            preserve_default=False,
        ),
    ]
