# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('futher_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('military', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=15)),
                ('child_num', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=30)),
                ('mobil', models.CharField(max_length=15)),
            ],
        ),
    ]
