# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=150)),
                ('score', models.CharField(max_length=4)),
                ('issued', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eucation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('majored', models.CharField(max_length=40)),
                ('field', models.CharField(max_length=50)),
                ('date_from', models.CharField(max_length=12)),
                ('date_to', models.CharField(max_length=12)),
                ('school', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('average', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('employment', models.CharField(max_length=20)),
                ('date_from', models.CharField(max_length=12)),
                ('date_to', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('futher_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('military', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=15)),
                ('child_num', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=30)),
                ('mobil', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='eucation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='computerlevel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation'),
        ),
    ]
