# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_eucation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=150)),
                ('score', models.CharField(max_length=4)),
                ('issued', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=12)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('employment', models.CharField(max_length=20)),
                ('date_from', models.CharField(max_length=12)),
                ('date_to', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=1000)),
                ('description', models.TimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation')),
            ],
        ),
        migrations.AddField(
            model_name='eucation',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employment.PersonalInformation'),
            preserve_default=False,
        ),
    ]
