# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20181120_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
